# Generated by Django 6.1 on 2026-08-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day', models.CharField(max_length=20)),
                ('activity', models.TextField()),
                ('skills_learned', models.TextField(blank=True)),
                ('challenges', models.TextField(blank=True)),
                ('supervisor_comment', models.TextField(blank=True)),
            ],
        ),
    ]
