# Generated by Django 6.1 on 2026-09-01 10:54

import django.db.models.deletion
import django.utils.timezone
import logbook.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=logbook.models.generate_otp, max_length=6)),
                ('type', models.CharField(choices=[('verify', 'Email Verification'), ('reset', 'Password Reset')], default='verify', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=logbook.models.get_verification_expiry)),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Email Verification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IndustrySupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone Number')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Company/Organization')),
                ('department', models.CharField(blank=True, max_length=200, verbose_name='Department/Unit')),
                ('job_title', models.CharField(blank=True, max_length=200, verbose_name='Job Title/Position')),
                ('employee_id', models.CharField(blank=True, max_length=100, verbose_name='Employee ID (optional)')),
                ('office_address', models.TextField(blank=True, verbose_name='Office Address (optional)')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Signature (image)')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='supervisor_pics/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Industry Supervisor',
            },
        ),
        migrations.CreateModel(
            name='SchoolSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone Number')),
                ('department', models.CharField(blank=True, max_length=200)),
                ('faculty', models.CharField(blank=True, max_length=200)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('staff_id', models.CharField(blank=True, max_length=100, verbose_name='Staff/ID Number')),
                ('position', models.CharField(blank=True, max_length=200)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Signature (image)')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='supervisor_pics/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School Supervisor',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('institution', models.CharField(blank=True, max_length=200, verbose_name='Institution/University')),
                ('course', models.CharField(blank=True, max_length=200, verbose_name='Course')),
                ('department', models.CharField(blank=True, max_length=200, verbose_name='Department')),
                ('matric_number', models.CharField(blank=True, max_length=50, verbose_name='Matric Number')),
                ('siwes_org', models.CharField(blank=True, max_length=200, verbose_name='SIWES Organization/Company')),
                ('siwes_start', models.DateField(blank=True, null=True, verbose_name='SIWES Start Date')),
                ('siwes_end', models.DateField(blank=True, null=True, verbose_name='SIWES End Date')),
                ('bio', models.TextField(blank=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Profile',
            },
        ),
        migrations.AlterModelOptions(
            name='dailyactivity',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Daily Activity', 'verbose_name_plural': 'Daily Activities'},
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/', verbose_name='Attachment (image/PDF/doc)'),
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='title',
            field=models.CharField(blank=True, max_length=300, verbose_name='Activity Title/Summary'),
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='what_learned',
            field=models.TextField(blank=True, verbose_name='What I Learned'),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='activity',
            field=models.TextField(verbose_name='Activity Description'),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='challenges',
            field=models.TextField(blank=True, verbose_name='Challenges Encountered'),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='day',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='skills_learned',
            field=models.TextField(blank=True, verbose_name='Skills / Technologies Used'),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='supervisor_comment',
            field=models.TextField(blank=True, verbose_name='Supervisor Comment'),
        ),
        migrations.AddIndex(
            model_name='dailyactivity',
            index=models.Index(fields=['user', 'date'], name='logbook_dai_user_id_5481d9_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyactivity',
            index=models.Index(fields=['user', '-date'], name='logbook_dai_user_id_ecb591_idx'),
        ),
        migrations.AddField(
            model_name='emailverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='industrysupervisor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='industry_supervisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolsupervisor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_supervisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
